id: I370F4FBF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T05:11:39+00:00'
last_modified: '2022-06-08T01:24:24.547069+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1892
  title: གངས་ལྗོངས་དམ་ཆོས་རིན་ཆེན་གཏེར་བུམ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    5C65:
      image_group_id: I1KG1922
      title: ''
      total_pages: 180
      order: 1
      base_file: 5C65.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
